imports:
    - { resource: config.yml }

doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver: pdo_mysql
          host: 127.0.0.1
          port: 3306
          dbname: reddin_task_db_dev
          user: root
          password: yourpassword
          charset: UTF8
          # if using pdo_sqlite as your database driver:
          #   1. add the path in parameters.yml
          #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
          #   2. Uncomment database_path in parameters.yml.dist
          #   3. Uncomment next line:
          #path: '%database_path%'
framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
