imports:
    - { resource: config_dev.yml }
doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver: pdo_mysql
          host: 127.0.0.1
          port: 3306
          dbname: reddin_task_db_test
          user: root
          password: yourpassword
          charset: UTF8
          # if using pdo_sqlite as your database driver:
          #   1. add the path in parameters.yml
          #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
          #   2. Uncomment database_path in parameters.yml.dist
          #   3. Uncomment next line:
          #path: '%database_path%'
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
